/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vishaluplanch.kafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Department extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8684029755593487591L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Department\",\"namespace\":\"com.vishaluplanch.kafka.avro.schema\",\"fields\":[{\"name\":\"departmentName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"departmentId\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Department> ENCODER =
      new BinaryMessageEncoder<Department>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Department> DECODER =
      new BinaryMessageDecoder<Department>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Department> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Department> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Department>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Department to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Department from a ByteBuffer. */
  public static Department fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence departmentName;
  @Deprecated public int departmentId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Department() {}

  /**
   * All-args constructor.
   * @param departmentName The new value for departmentName
   * @param departmentId The new value for departmentId
   */
  public Department(java.lang.CharSequence departmentName, java.lang.Integer departmentId) {
    this.departmentName = departmentName;
    this.departmentId = departmentId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return departmentName;
    case 1: return departmentId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: departmentName = (java.lang.CharSequence)value$; break;
    case 1: departmentId = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'departmentName' field.
   * @return The value of the 'departmentName' field.
   */
  public java.lang.CharSequence getDepartmentName() {
    return departmentName;
  }

  /**
   * Sets the value of the 'departmentName' field.
   * @param value the value to set.
   */
  public void setDepartmentName(java.lang.CharSequence value) {
    this.departmentName = value;
  }

  /**
   * Gets the value of the 'departmentId' field.
   * @return The value of the 'departmentId' field.
   */
  public java.lang.Integer getDepartmentId() {
    return departmentId;
  }

  /**
   * Sets the value of the 'departmentId' field.
   * @param value the value to set.
   */
  public void setDepartmentId(java.lang.Integer value) {
    this.departmentId = value;
  }

  /**
   * Creates a new Department RecordBuilder.
   * @return A new Department RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.Department.Builder newBuilder() {
    return new com.vishaluplanch.kafka.avro.schema.Department.Builder();
  }

  /**
   * Creates a new Department RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Department RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.Department.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.Department.Builder other) {
    return new com.vishaluplanch.kafka.avro.schema.Department.Builder(other);
  }

  /**
   * Creates a new Department RecordBuilder by copying an existing Department instance.
   * @param other The existing instance to copy.
   * @return A new Department RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.Department.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.Department other) {
    return new com.vishaluplanch.kafka.avro.schema.Department.Builder(other);
  }

  /**
   * RecordBuilder for Department instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Department>
    implements org.apache.avro.data.RecordBuilder<Department> {

    private java.lang.CharSequence departmentName;
    private int departmentId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.Department.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.departmentName)) {
        this.departmentName = data().deepCopy(fields()[0].schema(), other.departmentName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[1].schema(), other.departmentId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Department instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.Department other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.departmentName)) {
        this.departmentName = data().deepCopy(fields()[0].schema(), other.departmentName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[1].schema(), other.departmentId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'departmentName' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartmentName() {
      return departmentName;
    }

    /**
      * Sets the value of the 'departmentName' field.
      * @param value The value of 'departmentName'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.Department.Builder setDepartmentName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.departmentName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentName' field has been set.
      * @return True if the 'departmentName' field has been set, false otherwise.
      */
    public boolean hasDepartmentName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'departmentName' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.Department.Builder clearDepartmentName() {
      departmentName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'departmentId' field.
      * @return The value.
      */
    public java.lang.Integer getDepartmentId() {
      return departmentId;
    }

    /**
      * Sets the value of the 'departmentId' field.
      * @param value The value of 'departmentId'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.Department.Builder setDepartmentId(int value) {
      validate(fields()[1], value);
      this.departmentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentId' field has been set.
      * @return True if the 'departmentId' field has been set, false otherwise.
      */
    public boolean hasDepartmentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'departmentId' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.Department.Builder clearDepartmentId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Department build() {
      try {
        Department record = new Department();
        record.departmentName = fieldSetFlags()[0] ? this.departmentName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.departmentId = fieldSetFlags()[1] ? this.departmentId : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Department>
    WRITER$ = (org.apache.avro.io.DatumWriter<Department>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Department>
    READER$ = (org.apache.avro.io.DatumReader<Department>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
