/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vishaluplanch.kafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmployeeDepartment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3825019574783699400L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeDepartment\",\"namespace\":\"com.vishaluplanch.kafka.avro.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"default\":-1},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"departmentId\",\"type\":\"int\",\"default\":0},{\"name\":\"departmentName\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeDepartment> ENCODER =
      new BinaryMessageEncoder<EmployeeDepartment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeDepartment> DECODER =
      new BinaryMessageDecoder<EmployeeDepartment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmployeeDepartment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmployeeDepartment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmployeeDepartment>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmployeeDepartment to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmployeeDepartment from a ByteBuffer. */
  public static EmployeeDepartment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int departmentId;
  @Deprecated public java.lang.CharSequence departmentName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeDepartment() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param departmentId The new value for departmentId
   * @param departmentName The new value for departmentName
   */
  public EmployeeDepartment(java.lang.Long id, java.lang.CharSequence name, java.lang.Integer departmentId, java.lang.CharSequence departmentName) {
    this.id = id;
    this.name = name;
    this.departmentId = departmentId;
    this.departmentName = departmentName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return departmentId;
    case 3: return departmentName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: departmentId = (java.lang.Integer)value$; break;
    case 3: departmentName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'departmentId' field.
   * @return The value of the 'departmentId' field.
   */
  public java.lang.Integer getDepartmentId() {
    return departmentId;
  }

  /**
   * Sets the value of the 'departmentId' field.
   * @param value the value to set.
   */
  public void setDepartmentId(java.lang.Integer value) {
    this.departmentId = value;
  }

  /**
   * Gets the value of the 'departmentName' field.
   * @return The value of the 'departmentName' field.
   */
  public java.lang.CharSequence getDepartmentName() {
    return departmentName;
  }

  /**
   * Sets the value of the 'departmentName' field.
   * @param value the value to set.
   */
  public void setDepartmentName(java.lang.CharSequence value) {
    this.departmentName = value;
  }

  /**
   * Creates a new EmployeeDepartment RecordBuilder.
   * @return A new EmployeeDepartment RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder newBuilder() {
    return new com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder();
  }

  /**
   * Creates a new EmployeeDepartment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeDepartment RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder other) {
    return new com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder(other);
  }

  /**
   * Creates a new EmployeeDepartment RecordBuilder by copying an existing EmployeeDepartment instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeDepartment RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.EmployeeDepartment other) {
    return new com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder(other);
  }

  /**
   * RecordBuilder for EmployeeDepartment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeDepartment>
    implements org.apache.avro.data.RecordBuilder<EmployeeDepartment> {

    private long id;
    private java.lang.CharSequence name;
    private int departmentId;
    private java.lang.CharSequence departmentName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[2].schema(), other.departmentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.departmentName)) {
        this.departmentName = data().deepCopy(fields()[3].schema(), other.departmentName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeDepartment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.EmployeeDepartment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[2].schema(), other.departmentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.departmentName)) {
        this.departmentName = data().deepCopy(fields()[3].schema(), other.departmentName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'departmentId' field.
      * @return The value.
      */
    public java.lang.Integer getDepartmentId() {
      return departmentId;
    }

    /**
      * Sets the value of the 'departmentId' field.
      * @param value The value of 'departmentId'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder setDepartmentId(int value) {
      validate(fields()[2], value);
      this.departmentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentId' field has been set.
      * @return True if the 'departmentId' field has been set, false otherwise.
      */
    public boolean hasDepartmentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'departmentId' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder clearDepartmentId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'departmentName' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartmentName() {
      return departmentName;
    }

    /**
      * Sets the value of the 'departmentName' field.
      * @param value The value of 'departmentName'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder setDepartmentName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.departmentName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentName' field has been set.
      * @return True if the 'departmentName' field has been set, false otherwise.
      */
    public boolean hasDepartmentName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'departmentName' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.EmployeeDepartment.Builder clearDepartmentName() {
      departmentName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeDepartment build() {
      try {
        EmployeeDepartment record = new EmployeeDepartment();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.departmentId = fieldSetFlags()[2] ? this.departmentId : (java.lang.Integer) defaultValue(fields()[2]);
        record.departmentName = fieldSetFlags()[3] ? this.departmentName : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeDepartment>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeDepartment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeDepartment>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeDepartment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
